version: "2.1"
services:
  workstation:
    image: ${MS_IMAGE_PREFIX}/workstation:${MS_IMAGE_TAG}
    container_name: workstation
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${MS_MYSQL_HOST}:${MS_MYSQL_PORT}/${MS_MYSQL_DB}?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false&sessionVariables=sql_mode=%27STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION%27
      SPRING_DATASOURCE_USERNAME: ${MS_MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MS_MYSQL_PASSWORD}
      KAFKA_PARTITIONS: 4
      KAFKA_REPLICAS: 1
      KAFKA_TOPIC: ${MS_KAFKA_TOPIC}
      KAFKA_LOG_TOPIC: ${MS_KAFKA_LOG_TOPIC}
      KAFKA_TEST_TOPIC: ${MS_KAFKA_TEST_TOPIC}
      KAFKA_REPORT_TOPIC: ${MS_KAFKA_REPORT_TOPIC}
      KAFKA_BOOTSTRAP-SERVERS: ${MS_KAFKA_HOST}:${MS_KAFKA_PORT}
      JMETER_IMAGE: ${MS_JMETER_IMAGE}
      K8S_NODE-CONTROLLER-IMAGE: ${MS_IMAGE_PREFIX}/node-controller:${MS_IMAGE_TAG}
      TCP_MOCK_PORT: ${MS_TCP_MOCK_PORT}
      SPRING_SESSION_TIMEOUT: '30d'
      FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS: 'true'
      REDIS_HOST: ${MS_REDIS_HOST}
      REDIS_PORT: ${MS_REDIS_PORT}
      REDIS_PASSWORD: ${MS_REDIS_PASSWORD}
      MINIO_ENDPOINT: ${MS_MINIO_ENDPOINT}
      MINIO_ACCESS-KEY: ${MS_MINIO_ACCESS_KEY}
      MINIO_SECRET-KEY: ${MS_MINIO_SECRET_KEY}
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "8007"]
      interval: 6s
      timeout: 10s
      retries: 50
    restart: always
    volumes:
      - ms-conf:/opt/metersphere/conf
      - ms-logs:/opt/metersphere/logs
      - ms-data:/opt/metersphere/data
    mem_limit: ${MS_WORKSTATION_MEM_LIMIT:-858993459} # default 800m bytes
    networks:
      - ms-network
    depends_on:
      system-setting:
        condition: service_healthy