version: "2.1"
services:
    chrome:
        image: ${MS_IMAGE_PREFIX}/standalone-chrome:4.1.1
        container_name: ms-chrome
        expose:
          - 4444
        ports:
          - 4444:4444
        healthcheck:
          test: ["CMD", "nc", "-zv", "localhost", "4444"]
          interval: 6s
          timeout: 5s
          retries: 10          
        networks:
          - ms-network